name: base

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      pushImage:
        default: true
        type: boolean
    secrets:
      username:
        required: true
      password:
        required: true

jobs:
  baseimagebuild:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:qemu-v8.1.5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up cosign
        uses: sigstore/cosign-installer@main
      - name: Login to Quay
        if: ${{ inputs.pushImage }}
        uses: docker/login-action@v3
        with:
          registry: quay.io/rh-ee-asavage
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
      - name: Build and push a base image for building Kepler with libbpf
        id: build-push-image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./build/Dockerfile.builder
          platforms: linux/amd64,linux/arm64,linux/s390x
          push: ${{ inputs.pushImage }}
          tags: quay.io/rh-ee-asavage/kepler_builder:ubi-9-libbpf-1.3.0
      - name: Sign images with GitHub OIDC token
        run: |
          cosign sign -y quay.io/rh-ee-asavage/kepler_builder:ubi-9-libbpf-1.3.0@${{ steps.build-push-image.outputs.digest }}

      - name: Generate image attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: quay.io/rh-ee-asavage/kepler_builder
          subject-digest: ${{ steps.build-push-image.outputs.digest }}
          push-to-registry: true

