name: imagePRlevel

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      commitSHA:
        description: pr commit SHA
        required: true

jobs:
  image_build_for_specific_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commitSHA }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up cosign
        uses: sigstore/cosign-installer@main
      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io/rh-ee-asavage
          username: ${{ secrets.BOT_NAME }}
          password: ${{ secrets.BOT_TOKEN }}

      - name: Build and push
        id: build-push-image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: quay.io/rh-ee-asavage/kepler
          labels: ${{ github.event.inputs.commitSHA }}
          file: build/Dockerfile.libbpf.kepler

      - name: Sign images with GitHub OIDC token
        run: |
          cosign sign -y quay.io/rh-ee-asavage/kepler@${{ steps.build-push-image.outputs.digest }}

      - name: Generate image attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: quay.io/rh-ee-asavage/kepler
          subject-digest: ${{ steps.build-push-image.outputs.digest }}
          push-to-registry: true

